#!bin/bash

## Debug options ##
# If this options are set to - instead of +, debug option is active
set +x  # Command traces before executing commands
set +v  # Shell input lines as they are read

## Global Variables ##

declare -r PROJECT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
declare -r SHAREDCONTENT_FILE="${PROJECT_DIRECTORY}/`basename "${BASH_SOURCE[@]}"`"
declare -r DOCKERCOMPOSE_FILE="${PROJECT_DIRECTORY}/docker-compose.yml"

## Check Functions ##

isnumber() {
    [[ "$1" =~ ^-?[0-9]+$ ]]
}

_usage() {
    [[ -z "${USAGE_MESSAGE// }" ]] && echo "Undefined variable \$USAGE_MESSAGE in `basename "$0"`." || echo "Usage : `basename "$0"` $USAGE_MESSAGE"
    exit 1
}
